---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
  name: hello
spec:
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: hello
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
spec:
  rules:
    - host: 119-91-237-208.nip.io
      http:
        paths:
          - path: /hello-devops
            pathType: ImplementationSpecific
            backend:
              service:
                name: hello
                port:
                  number: 8888
